---
- name: Configure_IP_interface
  hosts: all
  gather_facts: no
  
  tasks: 
    - name: Configure_IP_ether3
      routeros_command:
        commands:
          - /ip address add interface=ether3 address=192.168.13.1/24 

    - name: Configure_IP_ether4
      routeros_command:
        commands:
          - /ip address add interface=ether4 address=192.168.14.1/24 

    - name: show_ip_interface
      routeros_command:
        commands:
          - /ip address print     
      register: IP_table

    - name: Display router IP
      debug:
        msg: "{{ item }}"
      loop: "{{ IP_table['stdout_lines'][0] }}"