---
- name: create vlan
  hosts: all
  gather_facts: no
  vars:
    vlans:
      - name: nhansu
        vlan_id: 104
        interface: ether2
      - name: intern
        vlan_id: 105
        interface: ether3

  tasks: 
    - name: create vlans
      routeros_command:
        commands:
        - /interface vlan add name="vlan{{item.vlan_id}}" interface="{{item.interface}}" comment="To {{ item.name }}" vlan-id="{{ item.vlan_id }}"    
      when:
        - vlans is define
      loop: "{{ vlans }}"
      tags:
        - vlans:


