---
- name: create vlan
  hosts: all
  gather_facts: no
  vlan:
    - name: nhansu
      vlan_id: 110
      interface: ether4
    - name: intern
      vlan_id: 111
      interface: ether5

  tasks: 
    - name: create vlans
      routeros_command:
        commands:
        # - /interface vlan add name="VLAN{{ item.vlan_id }}" interface="{{ item.interface }}" comment="To {{item.name}}" vlan-id="{{item.vlan_id}}"
        - /interface vlan add name="VLAN{{ item.vlan_id }}" interface="{{ item.interface }}" vlan-id="{{item.vlan_id}}"    
      when:
        - vlans is define
      loop: "{{ vlans }}"
      tags:
        - vlan:


