---
- name: create vlan
  hosts: all
  gather_facts: no
  # vars:
  #   vlans:
  #     - name: nhansu
  #       vlan_id: 104
  #       interface: ether2
  #     - name: intern
  #       vlan_id: 105
  #       interface: ether3

  tasks: 
    - name: create vlans
      routeros_command:
        commands:
        - /interface vlan add name="VLAN104" interface="ether2" vlan-id=104    
      # when:
      #   - vlans is define
      # loop: "{{ vlans }}"
      # tags:
      #   - vlans:


