---
- name: create vlan
  hosts: all
  gather_facts: no
  tasks: 
    - name: create vlans
      routeros_command:
        commands:
         - /interface vlan add name="VLAN110" interface="ether5" vlan-id=110


