---
- name: Turn_off_interface
  hosts: all
  gather_facts: no
  tasks: 
    # - name: Turn_off_ether10
    #   routeros_command:
    #     commands:
    #       - /interface ethernet disable ether10

    - name: show_interface_on
      routeros_command:
        commands:
          - /interface ethernet print brief
      register: interface_output

    - name: display_interface_on
      debug: 
        msg: "{{ item }}" 
      loop: "{{ interface_output['stdout_lines'][0] }}"    
        